// import {OfflineService} from '../modules/offline/shared/services/offline.service';
// import {NotificationService} from '../modules/notification/shared/services/notification.service';
// import {UserService} from '../modules/auth/shared/services/user.service';
// import {OfflineStore} from '../modules/offline/store/offline.store';
import {ContainerModule, interfaces} from 'inversify';
import {IntlStore} from '../modules/intl/store/intl.store';
import {ThemeStore} from '../modules/theme/store/theme.store';
import {DrawersPanelStore} from '../modules/navigation/store/drawers-panel.store';
import {NavigationPanelStore} from '../modules/navigation/store/navigation-panel.store';
import {AssetTypesService} from "../modules/asset-types/shared/services/asset-types.service";
import {AssetTypesStore} from "../modules/asset-types/store/asset-types.store";
import {CurrenciesStore} from "../modules/currencies/store/currencies.store";
import {CurrenciesService} from "../modules/currencies/shared/services/currencies.service";
import {StorageService} from "../shared/services/storage.service";
import {ExchangeStore} from "../modules/exchanges/store/exchange.store";
import {ExchangeService} from "../modules/exchanges/shared/services/exchange.service";
import {PortfoliosService} from "../modules/portfolios/shared/services/portfolios.service";
import {PortfoliosStore} from "../modules/portfolios/store/portfolios.store";
import {TransactionsStore} from "../modules/transactions/store/transactions.store";
import {TransactionsService} from "../modules/transactions/shared/services/transactions.service";
import {TransactionsTransferStore} from "../modules/transactions/store/transactions-transfer.store";
import {SettingsService} from "../modules/settings/shared/services/settings.service";
import {SettingsStore} from "../modules/settings/store/settings.store";
import {TickersStore} from "../modules/tickers/store/tickers.store";
import {TickersService} from "../modules/tickers/shared/services/tickers.service";
import {CurrencyRatesService} from "../modules/currencies/shared/services/currency-rates.service";
import {ManualStore} from "../modules/manual/store/manual.store";

export const IocModule = new ContainerModule((bind: interfaces.Bind) => {
  // bind('OfflineService').to(OfflineService).inSingletonScope();
  // bind('NotificationService').to(NotificationService).inSingletonScope();
  // bind('UserService').to(UserService).inSingletonScope();
  // bind('OfflineStore').to(OfflineStore).inSingletonScope();
  bind('StorageService').to(StorageService).inSingletonScope();
  bind('IntlStore').to(IntlStore).inSingletonScope();
  bind('ThemeStore').to(ThemeStore).inSingletonScope();
  bind('DrawersPanelStore').to(DrawersPanelStore).inSingletonScope();
  bind('NavigationPanelStore').to(NavigationPanelStore).inSingletonScope();
  bind('AssetTypesService').to(AssetTypesService).inSingletonScope();
  bind('AssetTypesStore').to(AssetTypesStore).inSingletonScope();
  bind('CurrenciesService').to(CurrenciesService).inSingletonScope();
  bind('CurrencyRatesService').to(CurrencyRatesService).inSingletonScope();
  bind('CurrenciesStore').to(CurrenciesStore).inSingletonScope();
  bind('ExchangeService').to(ExchangeService).inSingletonScope();
  bind('ExchangeStore').to(ExchangeStore).inSingletonScope();
  bind('PortfoliosService').to(PortfoliosService).inSingletonScope();
  bind('PortfoliosStore').to(PortfoliosStore).inSingletonScope();
  bind('TransactionsService').to(TransactionsService).inSingletonScope();
  bind('TransactionsStore').to(TransactionsStore).inSingletonScope();
  bind('TransactionsTransferStore').to(TransactionsTransferStore).inSingletonScope();
  bind('SettingsService').to(SettingsService).inSingletonScope();
  bind('SettingsStore').to(SettingsStore).inSingletonScope();
  bind('TickersService').to(TickersService).inSingletonScope();
  bind('TickersStore').to(TickersStore).inSingletonScope();
  bind('ManualStore').to(ManualStore).inSingletonScope();
});
